//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDONHANG
    {
        public int IDCTDONHANG { get; set; }
        public Nullable<int> DONGIA { get; set; }
        public Nullable<int> SOLUONGMUA { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public Nullable<int> IDSANPHAM { get; set; }
        public Nullable<int> IDDONHANG { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
