//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTGIAY
    {
        public int IDCTGIAY { get; set; }
        public Nullable<int> IDLOAISP { get; set; }
        public Nullable<int> IDSIZEGIAY { get; set; }
        public Nullable<int> IDTHGIAY { get; set; }
        public Nullable<int> IDSANPHAM { get; set; }
    
        public virtual LOAISP LOAISP { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual SIZEGIAY SIZEGIAY { get; set; }
        public virtual THGIAY THGIAY { get; set; }
    }
}
