//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTTHOITRANG
    {
        public int IDCTTHOITRANG { get; set; }
        public string CHATLIEU { get; set; }
        public Nullable<int> IDLOAISP { get; set; }
        public Nullable<int> IDTHTHOITRANG { get; set; }
        public Nullable<int> IDSIZETT { get; set; }
        public Nullable<int> IDSANPHAM { get; set; }
    
        public virtual LOAISP LOAISP { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual SIZETHOITRANG SIZETHOITRANG { get; set; }
        public virtual THTHOITRANG THTHOITRANG { get; set; }
    }
}
