//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIASP
    {
        public int IDDANHGIA { get; set; }
        public string DANHGIA { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<int> IDSANPHAM { get; set; }
        public Nullable<int> IDND { get; set; }
    
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
