//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;


    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            HINHANH1 = "~/Areas/Admin/Content/img/iconanh.png";
            HINHANH2 = "~/Areas/Admin/Content/img/iconanh.png";
            HINHANH3 = "~/Areas/Admin/Content/img/iconanh.png";
            this.CTDIENTHOAIs = new HashSet<CTDIENTHOAI>();
            this.CTDONHANGs = new HashSet<CTDONHANG>();
            this.CTGIAYs = new HashSet<CTGIAY>();
            this.CTTHOITRANGs = new HashSet<CTTHOITRANG>();
            this.DANHGIASPs = new HashSet<DANHGIASP>();
            this.NGUOIDUNGs = new HashSet<NGUOIDUNG>();
        }
        [NotMapped]
        public HttpPostedFileBase UploadImage1 { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImage2 { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImage3 { get; set; }
        public int IDSANPHAM { get; set; }
        public string TENSP { get; set; }
        public string HINHANH1 { get; set; }
        public string HINHANH2 { get; set; }
        public string HINHANH3 { get; set; }
        public string MOTASANPHAM { get; set; }
        [DisplayFormat(DataFormatString = "{0:0,0 đ}", ApplyFormatInEditMode = false)]
        public Nullable<int> GIABAN { get; set; }
        public Nullable<int> PHANTRAMGIAM { get; set; }
        [DisplayFormat(DataFormatString = "{0:0,0 đ}", ApplyFormatInEditMode = false)]
        public Nullable<int> GIAGIAM { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public Nullable<int> IDPHEDUYET { get; set; }
        public Nullable<int> IDCUAHANG { get; set; }
        public Nullable<int> IDLOAISP { get; set; }
        public Nullable<int> SOLUONGTON { get; set; }
        public Nullable<int> IDMAUSAC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDIENTHOAI> CTDIENTHOAIs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDONHANG> CTDONHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTGIAY> CTGIAYs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTTHOITRANG> CTTHOITRANGs { get; set; }
        public virtual CUAHANG CUAHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIASP> DANHGIASPs { get; set; }
        public virtual LOAISP LOAISP { get; set; }
        public virtual MAUSAC MAUSAC { get; set; }
        public virtual PHEDUYET PHEDUYET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGUOIDUNG> NGUOIDUNGs { get; set; }
    }
    // Decorator interface
    public interface IPromotionDecorator
    {
        int ApplyPromotion(int originalPrice);
    }

    // Concrete decorator
    public class PromotionDecorator : IPromotionDecorator
    {
        public int DiscountPercentage { get; set; }

        public PromotionDecorator(int discountPercentage)
        {
            DiscountPercentage = discountPercentage;
        }

        public int ApplyPromotion(int originalPrice)
        {
            // Apply the discount
            return originalPrice - (originalPrice * DiscountPercentage / 100);
        }
    }

    // Decorated SANPHAM class
    public class PromotedSANPHAM : SANPHAM
    {
        private IPromotionDecorator promotionDecorator;

        public PromotedSANPHAM(SANPHAM baseProduct, IPromotionDecorator promotionDecorator)
        {
            IDSANPHAM = baseProduct.IDSANPHAM;
            TENSP = baseProduct.TENSP;
            GIABAN = baseProduct.GIABAN;
            GIAGIAM = baseProduct.GIAGIAM;
            
            // Copy other properties...

            this.promotionDecorator = promotionDecorator;
        }

        public int GetDiscountedPrice()
        {
            // Use the decorator to calculate the discounted price
            return promotionDecorator.ApplyPromotion(GIAGIAM.Value);
        }
    }
}
