//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THDIENTHOAI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THDIENTHOAI()
        {
            this.CTDIENTHOAIs = new HashSet<CTDIENTHOAI>();
        }
        public List<THDIENTHOAI> ListBrand { get; set; }
        public int IDTHDIENTHOAI { get; set; }
        public string THUONGHIEUDT { get; set; }
        public Nullable<int> IDLOAISP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDIENTHOAI> CTDIENTHOAIs { get; set; }
        public virtual LOAISP LOAISP { get; set; }
    }
}
