//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THGIAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THGIAY()
        {
            this.CTGIAYs = new HashSet<CTGIAY>();
        }
        public List<THGIAY> ListBrands { get; set; }
        public int IDTHGIAY { get; set; }
        public string THUONGHIEUG { get; set; }
        public Nullable<int> IDLOAISP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTGIAY> CTGIAYs { get; set; }
        public virtual LOAISP LOAISP { get; set; }
    }
}
